name: "Backend Continuous Integration"

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
      
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main

#start of cdefing the jobs and their steps
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: pip install pipenv
        run: pip install pipenv --python /usr/bin/python3.8

      - name: Install dependencies
        run: cd starter/backend && pipenv install --dev

      - name: Run test
        run: cd starter/backend && pipenv run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: pip install pipenv
        run: pip install pipenv --python /usr/bin/python3.8

      - name: Install dependencies
        run: cd starter/backend && pipenv install --dev

      - name: Run lint
        run: cd starter/backend && pipenv run lint

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: pip install pipenv
        run: pip install pipenv --python /usr/bin/python3.8

      - name: Install dependencies
        run: cd starter/backend && pipenv install --dev

      - name: build mp-backend docker image
        run: cd starter/backend && docker build --tag mp-backend:latest .


